import { api } from "../client.js";

export const approvalTools = [
  { name: "list_approvals", description: "List approval requests for a company", inputSchema: { type: "object", properties: { companyId: { type: "string" }, status: { type: "string", enum: ["pending", "approved", "rejected", "revision_requested"] } }, required: ["companyId"] }, handler: async ({ companyId, status }: { companyId: string; status?: string }) => api(`/companies/${companyId}/approvals${status ? `?status=${status}` : ""}`) },
  { name: "get_approval", description: "Get details of an approval request", inputSchema: { type: "object", properties: { approvalId: { type: "string" } }, required: ["approvalId"] }, handler: async ({ approvalId }: { approvalId: string }) => api(`/approvals/${approvalId}`) },
  { name: "approve_request", description: "Approve a pending approval", inputSchema: { type: "object", properties: { approvalId: { type: "string" }, decisionNote: { type: "string" } }, required: ["approvalId"] }, handler: async ({ approvalId, decisionNote }: { approvalId: string; decisionNote?: string }) => api(`/approvals/${approvalId}/approve`, { method: "POST", body: { decisionNote } }) },
  { name: "reject_request", description: "Reject a pending approval", inputSchema: { type: "object", properties: { approvalId: { type: "string" }, decisionNote: { type: "string" } }, required: ["approvalId"] }, handler: async ({ approvalId, decisionNote }: { approvalId: string; decisionNote?: string }) => api(`/approvals/${approvalId}/reject`, { method: "POST", body: { decisionNote } }) },
  { name: "request_revision", description: "Request revisions on an approval", inputSchema: { type: "object", properties: { approvalId: { type: "string" }, decisionNote: { type: "string", description: "What needs revision" } }, required: ["approvalId", "decisionNote"] }, handler: async ({ approvalId, decisionNote }: { approvalId: string; decisionNote: string }) => api(`/approvals/${approvalId}/request-revision`, { method: "POST", body: { decisionNote } }) },
];
